Validating found git in: git
Using git 2.33.0 from git
> git rev-parse --git-dir
Open repository: /home/qtile/.config
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/main refs/remotes/main
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git show --textconv :qtile/config.py
> git ls-files --stage -- /home/qtile/.config/qtile/config.py
> git cat-file -s f14b9c87e9cabdd745dfdb2c39bf0cbb9527f2f3
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git show --textconv :qtile/config.py
> git ls-files --stage -- /home/qtile/.config/qtile/config.py
> git cat-file -s f14b9c87e9cabdd745dfdb2c39bf0cbb9527f2f3
Opening repository for path='/usr/lib/python3.9/site-packages/libqtile' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}
> git show --textconv :qtile/config.py
> git ls-files --stage -- /home/qtile/.config/qtile/config.py
> git cat-file -s f14b9c87e9cabdd745dfdb2c39bf0cbb9527f2f3
Opening repository for path='/usr/lib/python3.9/site-packages/libqtile/layout' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}
Opening repository for path='/usr/lib/python3.9/site-packages/libqtile' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}
Opening repository for path='/home/qtile/.vscode-oss/extensions/ms-python.python-2021.8.1159798656/pythonFiles/lib/python/jedi/third_party/typeshed/stdlib/2and3' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}
Opening repository for path='/usr/lib/python3.9/site-packages/libqtile' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}
